# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    ConnectedServiceName: 'Microsoft Azure Internal Consumption'
    subscriptionName: 'b2d5d77b-1847-4b3e-a534-838239ecfca3'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'NetworkWatcherRG'
    location: 'South Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateAzureStorage/azuredeploy.json'
    deploymentMode: 'Incremental'